export const GETTING_NEWS_WAITING = "GETTING_NEWS_WAITING";
export const GETTING_NEWS_FAILED  = "GETTING_NEWS_FAILED";
export const GETTING_NEWS_SUCCESS_INITIAL = "GETTING_NEWS_SUCCESS_INITIAL";
export const GETTING_NEWS_SUCCESS_GREATER_THAN = "GETTING_NEWS_SUCCESS_GREATER_THAN";
export const GETTING_NEWS_SUCCESS_LOWER_THAN = "GETTING_NEWS_SUCCESS_LOWER_THAN";
